# Generated by Django 5.1.1 on 2024-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='end_time',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='start_time',
            field=models.CharField(max_length=12),
        ),
    ]
