# Generated by Django 5.1.1 on 2024-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0002_alter_subtitle_end_time_alter_subtitle_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
